packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - browser-tabs-lock
  - core-js
  - esbuild

updateConfig:
  ignoreDependencies:
    - '@types/node'


# Default catalog: Expo's strict requirement
catalog:
  react: 19.1.0
  react-dom: 19.1.0
  "@types/react": ^19.1.0
  "@types/react-dom": ^19.1.0

# Web can use latest
catalogs:
  web:
    react: 19.2.4
    react-dom: 19.2.4
    "@types/react": ^19.2.0
    "@types/react-dom": ^19.2.0